# For local testing
services:
  postgres:
    image: postgres:16
    container_name: bundles-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine
    container_name: bundles-hasura
    ports:
      - "8082:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: admin
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: user
    depends_on:
      postgres:
        condition: service_healthy

  reverse-proxy:
    image: nginx:alpine
    container_name: bundles-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d:ro
    depends_on:
      - hasura

volumes:
  pgdata:
